### ISSUE TITLE
M1 mac: `make build` quits with exit code `2`: `make: *** [build.stamp] Error 245`

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/Unified-Font-Repository#57] opened 2021-10-20 06:15 UTC
On an M1 Mac, `make build` quits with exit code `2`: `make: *** [build.stamp] Error 245`

I see some files are built, but it's not clear if all the files were built successfully and the process finished.

This is similar to another issue: https://github.com/googlefonts/Unified-Font-Repository/issues/56

**Comment by simoncozens** [comment] 2022-03-07 12:58
OK, can now reproduce! The error 245 is coming from the gftools builder. Time to find out why...

**Comment by simoncozens** [comment] 2022-03-07 14:01
It is. I've provided a workaround for that in https://github.com/fonttools/ttfautohint-py/pull/18 . Closing here because it's not strictly a UFR bug and hopefully will be fixed when that PR is merged.

**Closed by simoncozens** 2022-03-07 14:01 UTC
